### ISSUE TITLE
Неправильное преобразование в ошибку

### ISSUE THREAD

**Issue by rusmaxim** [calibr/eh-api-client#2]
Note-api-service выдает ошибку строкой

Cannot POST /note/nb4

```
rror
evernote-sync_1  |     at buildError (/usr/src/app/node_modules/eh-api-client/lib/client.js:33:15)
evernote-sync_1  |     at /usr/src/app/node_modules/eh-api-client/lib/client.js:179:20
evernote-sync_1  |     at Request._callback (/usr/src/app/node_modules/eh-api-client/lib/client.js:235:10)
evernote-sync_1  |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:187:22)
evernote-sync_1  |     at emitTwo (events.js:106:13)
evernote-sync_1  |     at Request.emit (events.js:191:7)
evernote-sync_1  |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1044:10)
evernote-sync_1  |     at emitOne (events.js:96:13)
evernote-sync_1  |     at Request.emit (events.js:188:7)
evernote-sync_1  |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:965:12)
evernote-sync_1  |     at emitNone (events.js:91:20)
evernote-sync_1  |     at IncomingMessage.emit (events.js:185:7)
evernote-sync_1  |     at endReadableNT (_stream_readable.js:926:12)
evernote-sync_1  |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
evernote-sync_1  |     at process._tickCallback (internal/process/next_tick.js:98:9) httpStatus: 404
```

В итоге там неверное приводится ошибка.

**Comment by rusmaxim** [comment]
@calibr Повторно наткнулся на подобную проблему. Когда NGINX возвращает строку например Cannot GET / то при преобразовании ошибки происходит ошибка.  Наверное стоит поправить.
